name: Run Build on Windows

on:
  workflow_dispatch:

jobs:
  run-build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Run run_build.ps1 via Task Scheduler
        shell: powershell
        run: |
          schtasks /create /tn "RunBuild" /tr "powershell -WindowStyle Normal -File C:\Users\pkummara\run_build.ps1" /sc once /st 00:00 /rl HIGHEST /it /f
          schtasks /run /tn "RunBuild"
