name: Run SED Build on Windows

on:
  workflow_dispatch:

jobs:
  run-build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Run run_build.ps1 detached via WMI
        shell: powershell
        run: |
          $wmi = [wmiclass]"\\.\root\cimv2:Win32_Process"
          $wmi.Create("powershell -NoExit -WindowStyle Normal -File C:\Users\pkummara\run_build.ps1")
